name: Basic Quality Control

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build-frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Angular Environment Files
        working-directory: ./frontend
        run: |
          mkdir -p ./src/environments

          # environment.ts (development)
          echo "export const environment = {" > ./src/environments/environment.ts
          echo "  production: false," >> ./src/environments/environment.ts
          echo "  apiUrl: '${{ secrets.API_URL }}'," >> ./src/environments/environment.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'" >> ./src/environments/environment.ts
          echo "};" >> ./src/environments/environment.ts

          # environment.prod.ts (production)
          echo "export const environment = {" > ./src/environments/environment.prod.ts
          echo "  production: true," >> ./src/environments/environment.prod.ts
          echo "  apiUrl: '${{ secrets.API_URL }}'," >> ./src/environments/environment.prod.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'" >> ./src/environments/environment.prod.ts
          echo "};" >> ./src/environments/environment.prod.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

  frontend-unit-tests:
    name: Unit Tests Frontend
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Create Angular Environment Files
        working-directory: ./frontend
        run: |
          mkdir -p ./src/environments

          # environment.ts (development)
          echo "export const environment = {" > ./src/environments/environment.ts
          echo "  production: false," >> ./src/environments/environment.ts
          echo "  apiUrl: '${{ secrets.API_URL }}'," >> ./src/environments/environment.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'" >> ./src/environments/environment.ts
          echo "};" >> ./src/environments/environment.ts

          # environment.prod.ts (production)
          echo "export const environment = {" > ./src/environments/environment.prod.ts
          echo "  production: true," >> ./src/environments/environment.prod.ts
          echo "  apiUrl: '${{ secrets.API_URL }}'," >> ./src/environments/environment.prod.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'" >> ./src/environments/environment.prod.ts
          echo "};" >> ./src/environments/environment.prod.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Unit Tests
        run: npm run test
        working-directory: ./frontend